### ISSUE TITLE
Panic goroutine

### ISSUE THREAD

**Issue by diaskooo** [ying32/govcl#14]
```go package main

import (
	"github.com/ying32/govcl/vcl"
)

var (
	mainForm *vcl.TForm
)

func main() {
	vcl.Application.Initialize()
	mainForm = vcl.Application.CreateForm()
	mainForm.SetCaption("Hello")
	mainForm.ScreenCenter()

	Btn1 := vcl.NewButton(mainForm)
	Btn1.SetParent(mainForm)
	Btn1.SetBounds(10, 10, 88, 28)
	Btn1.SetCaption("Button1")
	Btn1.SetOnClick(func(sender vcl.IObject) {
		go func() {
			vcl.ShowMessage("Hello!")
		}()
	})

	vcl.Application.Run()
}

> fatal error: unexpected signal during runtime execution
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x84 pc=0x7fe1064fdea4]

**Comment by ying32** [comment]
All UI components are non-thread safe. If you want to use UI components in a coroutine, you need to use vcl.ThreadSync().

**Comment by diaskooo** [comment]
THX, close issus

**Comment by diaskooo** [comment]
```go
Btn1.SetOnClick(func(sender vcl.IObject) {
    go func() {
          vcl.ThreadSync(func() {
               vcl.ShowMessage("Hello!")
         })
    }()
})

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x84 pc=0x7fa6a642aea4]

**Comment by ying32** [comment]
I have not tested this problem. I don't know which version of golang and operating system you are using. Is it libvcl or liblcl?

**Comment by diaskooo** [comment]
**operating system**

> Ubuntu 18.04.1 LTS
>  Linux  4.15.0-38-generic

**golang version**

> go version go1.11.2 linux/amd64

**liblcl**

> 1.2.0

**Comment by diaskooo** [comment]
```fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x84 pc=0x7f11b1671ea4]

runtime stack:
runtime.throw(0x73e284, 0x2a)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x68e210, 0xc000117a00, 0xc00004a9f8)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0001179d0 sp=0xc000117998 pc=0x40439e
test/vendor/github.com/ying32/govcl/vcl/dylib._Cfunc_Syscall3(0x7f11b1c2bf30, 0x7f11b1c2bf70, 0x1, 0x7f11b700c8f0, 0x0)
        _cgo_gotypes.go:183 +0x4e fp=0xc000117a00 sp=0xc0001179d0 pc=0x4b366e
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal.func4(0x7f11b1c2bf30, 0x7f11b1c2bf70, 0x1, 0x7f11b700c8f0, 0x0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:281 +0xf9 fp=0xc000117a38 sp=0xc000117a00 pc=0x4b65d9
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal(0xc00008a020, 0xc00004ab40, 0x3, 0x3, 0x0, 0x0, 0x0, 0x7f11b1c3ce80)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:281 +0x1c1 fp=0xc000117ac8 sp=0xc000117a38 pc=0x4b5d11
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyDLL).call(0xc00009a040, 0xc000102f80, 0xc00004af28, 0x1, 0x1, 0x0, 0xc00004af20, 0x4c837d, 0xc00009d4e0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:204 +0xf8 fp=0xc000117e90 sp=0xc000117ac8 pc=0x4b4a98
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).Call(0xc000102f80, 0xc00004af28, 0x1, 0x1, 0x0, 0x7f11b70159b0, 0x68d790, 0xc00004af48)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:263 +0x52 fp=0xc000117ee8 sp=0xc000117e90 pc=0x4b5b02
test/vendor/github.com/ying32/govcl/vcl/api.Application_Run(0x7f11b700c8f0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/api/applicationdef.go:14 +0x5c fp=0xc000117f40 sp=0xc000117ee8 pc=0x4b7f9c
test/vendor/github.com/ying32/govcl/vcl.(*TApplication).Run(0xc000103840)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/applicationdef.go:68 +0x2f fp=0xc000117f58 sp=0xc000117f40 pc=0x62d79f
main.main()
        /home/go/src/test/temp/main.go:29 +0x159 fp=0xc000117f98 sp=0xc000117f58 pc=0x68d6d9
runtime.main()
        /usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000117fe0 sp=0xc000117f98 pc=0x42c4b7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000117fe8 sp=0xc000117fe0 pc=0x454e51

goroutine 19 [syscall, locked to thread]:
test/vendor/github.com/ying32/govcl/vcl/dylib._Cfunc_Syscall3(0x7f11b1c2bf30, 0x7f11b1c33100, 0x1, 0xc000112d40, 0x0)
        _cgo_gotypes.go:183 +0x4e
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal.func4(0x7f11b1c2bf30, 0x7f11b1c33100, 0x1, 0xc000112d40, 0x0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:281 +0xf9
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal(0xc00008a020, 0xc000112930, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:281 +0x1c1
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyDLL).call(0xc00009a040, 0xc0001031c0, 0xc000112d18, 0x1, 0x1, 0x2, 0x20, 0x7, 0xc000112d40)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:204 +0xf8
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).Call(0xc0001031c0, 0xc000112d18, 0x1, 0x1, 0x7, 0x20, 0x7, 0x0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:263 +0x52
test/vendor/github.com/ying32/govcl/vcl/api.DShowMessage(0x6f10f4, 0x6)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/api/dfuncs.go:64 +0x78
test/vendor/github.com/ying32/govcl/vcl.ShowMessage(0x6f10f4, 0x6)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/funcs.go:15 +0x35
main.main.func1.1.1()
        /home/go/src/test/temp/main.go:24 +0x36
test/vendor/github.com/ying32/govcl/vcl.callbackProc(0x68d700, 0x0, 0x0, 0xc00004f8a0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/callback.go:266 +0x1013
test/vendor/github.com/ying32/govcl/vcl.doCallbackProc(0x68d700, 0x0, 0x0, 0x0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/callback_posix.go:17 +0x3f
test/vendor/github.com/ying32/govcl/vcl._cgoexpwrap_5903dd60daf4_doCallbackProc(0x68d700, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:62 +0x72
test/vendor/github.com/ying32/govcl/vcl/dylib._Cfunc_Syscall3(0x7f11b1c2bf30, 0x7f11b1c33120, 0x1, 0x68d700, 0x0)
        _cgo_gotypes.go:183 +0x4e
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal.func4(0x7f11b1c2bf30, 0x7f11b1c33120, 0x1, 0x68d700, 0x0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:281 +0xf9
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal(0xc00008a020, 0xc00004fba8, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:281 +0x1c1
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyDLL).call(0xc00009a040, 0xc000103280, 0xc00004ff90, 0x1, 0x1, 0xc000086538, 0x68d700, 0x6bbee0, 0x73f7a0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:204 +0xf8
test/vendor/github.com/ying32/govcl/vcl/dylib.(*LazyProc).Call(0xc000103280, 0xc000038790, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:263 +0x52
test/vendor/github.com/ying32/govcl/vcl/api.DSynchronize(0x6bbee0, 0x73f7a0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/api/dfuncs.go:127 +0x74
test/vendor/github.com/ying32/govcl/vcl.ThreadSync(0x73f7a0)
        /home/go/src/test/vendor/github.com/ying32/govcl/vcl/funcs.go:47 +0x37
main.main.func1.1()
        /home/go/src/test/temp/main.go:23 +0x2d
created by main.main.func1
        /home/go/src/test/temp/main.go:22 +0x35
exit status 2
