### ISSUE TITLE
MacOS13.3错误

### ISSUE THREAD

**Issue by yundmb** [ying32/govcl#170]
# vcl
ld: warning: object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000003.o) was built for newer macOS version (13.0) than being linked (10.8)ld: warning: ld: warning: ld: warning: ld: warning: object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000005.o) was built for newer macOS version (13.0) than being linked (10.8)
ld: warning: object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000006.o) was built for newer macOS version (13.0) than being linked (10.8)
object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000010.o) was built for newer macOS version (13.0) than being linked (10.8)
object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000004.o) was built for newer macOS version (13.0) than being linked (10.8)
ld: warning: object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000007.o) was built for newer macOS version (13.0) than being linked (10.8)
ld: warning: ld: warning: ld: warning: 
object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000011.o) was built for newer macOS version (13.0) than being linked (10.8)object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000009.o) was built for newer macOS version (13.0) than being linked (10.8)
ld: warning: object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000008.o) was built for newer macOS version (13.0) than being linked (10.8)
object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000012.o) was built for newer macOS version (13.0) than being linked (10.8)
object file (/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/go-link-530526764/000002.o) was built for newer macOS version (13.0) than being linked (10.8)

/private/var/folders/8y/sj3hxt4n5bg4vvryb6bjz97r0000gn/T/GoLand/___go_build_vcl
dlopen err: dlopen(liblcl.dylib, 0x0009): tried: 'liblcl.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblcl.dylib' (no such file), '/usr/lib/liblcl.dylib' (no such file, not in dyld cache), 'liblcl.dylib' (no such file), '/usr/local/lib/liblcl.dylib' (no such file), '/usr/lib/liblcl.dylib' (no such file, not in dyld cache)
panic: dlopen("liblcl.dylib"), failed.

goroutine 1 [running]:
github.com/ying32/govcl/vcl/api.loadUILib()
        /Users/xxx/.go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/api/dylib_nonmemory.go:32 +0xd8
github.com/ying32/govcl/vcl/api.init()
        /Users/xxx/.go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/api/dylib.go:24 +0x13e

**Comment by ying32** [comment]
这是你没看这个项目里得readme和或者文档

**Comment by mainlxl** [comment]
[liblcl.dylib.zip](https://github.com/ying32/govcl/files/13555838/liblcl.dylib.zip)
昨天追着文档编译了一遍2.2.3

**Comment by mainlxl** [comment]
就是我在demo上 加上_ "github.com/ying32/govcl/pkgs/macapp" 跑demo时 第一没啥问题 关了马上运行第二次就崩溃 
<img width="867" alt="image" src="https://github.com/ying32/govcl/assets/16352477/d4055ff7-545b-45c0-b034-f58130aa9d3d">
过一会又可以运行

**Comment by ying32** [comment]
看这异常报是的代码签名的问题。。。

**Comment by mainlxl** [comment]
是macapp的壳的签名么？
