### ISSUE TITLE
Setting color colors.ClGray to canvas pen or brush of a form struct which has colorbox and toolbar field, crashes the program.

### ISSUE THREAD

**Issue by brokenarmor451** [ying32/govcl#175]
This code crashes the program:
```
package main

import (
    _ "github.com/ying32/govcl/pkgs/winappres"
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types/colors"
)

type TForm1 struct {
    *vcl.TForm
    PaintBox1 *vcl.TPaintBox
    // problem is here which making two
    // fields colordialog and toolbar
    ColorDialog1 *vcl.TColorDialog
    ToolBar1 *vcl.TToolBar
}

var Form1 *TForm1

func (f *TForm1) OnFormCreate(sender vcl.IObject) {
    f.PaintBox1 = vcl.NewPaintBox(f)
    f.PaintBox1.SetParent(f)
    
    canvas := f.PaintBox1.Canvas()
    
    canvas.Pen().SetColor(colors.ClGray)
    canvas.Rectangle(0,0,100, 100)
}

func main() {

	vcl.Application.Initialize()
	vcl.Application.SetMainFormOnTaskBar(true)
	vcl.Application.CreateForm(&Form1)
	vcl.Application.Run()

}
```
```
Library Version: 2.2.0
runtime: bad pointer in frame github.com/ying32/dylib.(*LazyProc).CallOriginal.func5 at 0xc00012aaf8: 0x2
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw({0x5fa639?, 0x7ce2c0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ffdfa8f0ba0 sp=0x7ffdfa8f0b70 pc=0x435b7d
runtime.adjustpointers(0x7ffdfa8f0f98?, 0x0?, 0x6e3efe?, {0x741b90?, 0x7ce2c0?})
        /usr/local/go/src/runtime/stack.go:632 +0x1d0 fp=0x7ffdfa8f0c08 sp=0x7ffdfa8f0ba0 pc=0x44cc50
runtime.adjustframe(0x7ffdfa8f0f98, 0x7ffdfa8f1078)
        /usr/local/go/src/runtime/stack.go:674 +0xc9 fp=0x7ffdfa8f0c98 sp=0x7ffdfa8f0c08 pc=0x44cd69
runtime.gentraceback(0x0?, 0x0?, 0xc?, 0xc0000061a0, 0x0, 0x0, 0x7fffffff, 0x6006b8, 0x0?, 0x0)
        /usr/local/go/src/runtime/traceback.go:332 +0xbee fp=0x7ffdfa8f0ff0 sp=0x7ffdfa8f0c98 pc=0x457d8e
runtime.copystack(0xc0000061a0, 0x800000002?)
        /usr/local/go/src/runtime/stack.go:934 +0x2f5 fp=0x7ffdfa8f11a8 sp=0x7ffdfa8f0ff0 pc=0x44d595
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:1114 +0x485 fp=0x7ffdfa8f1358 sp=0x7ffdfa8f11a8 pc=0x44db05
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:574 +0x8b fp=0x7ffdfa8f1360 sp=0x7ffdfa8f1358 pc=0x462dcb

goroutine 1 [copystack, locked to thread]:
runtime.resolveTypeOff(0x5bf640?, 0x18d80)
        /usr/local/go/src/runtime/type.go:230 +0x299 fp=0xc00012a358 sp=0xc00012a350 pc=0x45b919
runtime.(*_type).typeOff(...)
        /usr/local/go/src/runtime/type.go:269
runtime.(*itab).init(0x7f4c0ad93a58)
        /usr/local/go/src/runtime/iface.go:210 +0x165 fp=0xc00012a408 sp=0xc00012a358 pc=0x40c985
runtime.getitab(0x5bf640, 0x5be1a0, 0x1)
        /usr/local/go/src/runtime/iface.go:76 +0x136 fp=0xc00012a450 sp=0xc00012a408 pc=0x40c456
runtime.assertE2I2(0x0?, {0x5be1a0?, 0xc0001148f0?})
        /usr/local/go/src/runtime/iface.go:461 +0x34 fp=0xc00012a480 sp=0xc00012a450 pc=0x40d454
fmt.(*pp).handleMethods(0xc00007a000, 0x5f8e31?)
        /usr/local/go/src/fmt/print.go:637 +0x9e fp=0xc00012a6d0 sp=0xc00012a480 pc=0x4ce39e
fmt.(*pp).printArg(0xc00007a000, {0x5be1a0?, 0xc0001148f0}, 0x76)
        /usr/local/go/src/fmt/print.go:756 +0x69b fp=0xc00012a770 sp=0xc00012a6d0 pc=0x4cf15b
fmt.(*pp).doPrintln(0xc00007a000, {0xc00012a858?, 0x2, 0x0?})
        /usr/local/go/src/fmt/print.go:1223 +0x3e fp=0xc00012a7e0 sp=0xc00012a770 pc=0x4d2b3e
fmt.Fprintln({0x636668, 0xc0000b2008}, {0xc0000a0858, 0x2, 0x2})
        /usr/local/go/src/fmt/print.go:304 +0x4f fp=0xc00012a830 sp=0xc00012a7e0 pc=0x4cc1ef
fmt.Println(...)
        /usr/local/go/src/fmt/print.go:314
github.com/ying32/govcl/vcl.callEvent.func1()
        /home/user/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/autoBindEvents.go:209 +0x73 fp=0xc00012a888 sp=0xc00012a830 pc=0x57f553
runtime.deferCallSave(0xc00012a958, 0x600568?)
        /usr/local/go/src/runtime/panic.go:796 +0x88 fp=0xc00012a898 sp=0xc00012a888 pc=0x435328
runtime.runOpenDeferFrame(0xc000117090)
        /usr/local/go/src/runtime/panic.go:769 +0x1b4 fp=0xc00012a8e0 sp=0xc00012a898 pc=0x435154
panic({0x5be1a0, 0xc0001148f0})
        /usr/local/go/src/runtime/panic.go:884 +0x213 fp=0xc00012a9a0 sp=0xc00012a8e0 pc=0x435593
runtime.cgoCheckUnknownPointer(0x808080, {0x5fd83c, 0x29})
        /usr/local/go/src/runtime/cgocall.go:589 +0x169 fp=0xc00012a9f8 sp=0xc00012a9a0 pc=0x407009
runtime.cgoCheckArg(0x5b5460, 0x808080, 0x0?, 0x1, {0x5fd83c, 0x29})
        /usr/local/go/src/runtime/cgocall.go:555 +0x285 fp=0xc00012aa70 sp=0xc00012a9f8 pc=0x406bc5
runtime.cgoCheckPointer({0x5b5460, 0x808080}, {0x0, 0x0})
        /usr/local/go/src/runtime/cgocall.go:436 +0x165 fp=0xc00012aab8 sp=0xc00012aa70 pc=0x4068e5
github.com/ying32/dylib.(*LazyProc).CallOriginal.func5(0x4d91e0?, {0xc0000a0c18?, 0xc0001148e0?, 0xc0000a0b20?})
        /home/user/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:284 +0xdc fp=0xc00012ab20 sp=0xc00012aab8 pc=0x4daedc
github.com/ying32/dylib.(*LazyProc).CallOriginal(0xc00009a1e0, {0xc0000a0c18, 0x4, 0x4})
        /home/user/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:284 +0xf7 fp=0xc00012ab98 sp=0xc00012ab20 pc=0x4d93b7
github.com/ying32/dylib.(*LazyDLL).call(0xc0000b8000, 0xc000122000, {0xc0000a0f70?, 0x2, 0xc00001a470?})
        /home/user/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:201 +0x18b fp=0xc00012af48 sp=0xc00012ab98 pc=0x4d84eb
github.com/ying32/dylib.(*LazyProc).Call(...)
        /home/user/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:264
github.com/ying32/govcl/vcl/api.Pen_SetColor(0x7f4c0b6045e0, 0x808080)
        /home/user/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/api/importFuncsAuto.go:32694 +0x65 fp=0xc00012af90 sp=0xc00012af48 pc=0x5046e5
github.com/ying32/govcl/vcl.(*TPen).SetColor(...)
        /home/user/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/pen.go:213
main.(*TForm1).OnFormCreate(0xc00002c0e0, {0x0?, 0x0?})
        /home/user/xxx/xxx/xxx/xxx/report/main.go:24 +0x7d fp=0xc00012afc0 sp=0xc00012af90 pc=0x589ebd
runtime.call32(0xc000077e90, 0xc0000155f0, 0x0, 0x0, 0x0, 0x18, 0xc0000a1500)
        /usr/local/go/src/runtime/asm_amd64.s:729 +0x49 fp=0xc00012aff0 sp=0xc00012afc0 pc=0x463269
runtime.reflectcall(0x5e4c80?, 0xc00002c0e0?, 0x4?, 0x5ef71c?, 0x0?, 0x12?, 0x5cc080?)
        <autogenerated>:1 +0x3c fp=0xc00012b030 sp=0xc00012aff0 pc=0x4678fc
reflect.Value.call({0x5e4c80?, 0xc00002c0e0?, 0x5?}, {0x5e9965, 0x4}, {0xc0000a17c8, 0x1, 0x5362d5?})
        /usr/local/go/src/reflect/value.go:586 +0xb0b fp=0xc00012b620 sp=0xc00012b030 pc=0x489f0b
reflect.Value.Call({0x5e4c80?, 0xc00002c0e0?, 0x0?}, {0xc0000a17c8?, 0x0?, 0x0?})
        /usr/local/go/src/reflect/value.go:370 +0xbc fp=0xc00012b698 sp=0xc00012b620 pc=0x4891bc
github.com/ying32/govcl/vcl.callEvent({0x5e4c80?, 0xc00002c0e0?, 0x0?}, {0xc0000a17c8?, 0x6383c0?, 0xc000068480?})
        /home/user/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/autoBindEvents.go:216 +0x85 fp=0xc00012b6e8 sp=0xc00012b698 pc=0x53d465
github.com/ying32/govcl/vcl.autoBindEvents({0x5e4c80?, 0xc00002c0e0?, 0xc0000a1d10?}, {0x637f08, 0xc00002c100}, 0x0, 0x1d?)
        /home/user/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/autoBindEvents.go:177 +0x669 fp=0xc00012bcf8 sp=0xc00012b6e8 pc=0x53ca49
github.com/ying32/govcl/vcl.fullFiledVal({0x637f08, 0xc00002c100}, {0x5e4c80?, 0xc00002c0e0?, 0xc00007a0d8?}, 0x0, 0x1e?)
        /home/user/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/resform.go:124 +0x286 fp=0xc00012bd98 sp=0xc00012bcf8 pc=0x56b846
github.com/ying32/govcl/vcl.resObjectBuild(0x0, {0x0?, 0x0}, 0xc000077350?, {0xc0000a1f60, 0x1, 0x1?})
        /home/user/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/resform.go:235 +0x7eb fp=0xc00012bee8 sp=0xc00012bd98 pc=0x56c14b
github.com/ying32/govcl/vcl.(*TApplication).CreateForm(0x7f4c0b5c48f0?, {0xc0000a1f60?, 0x0?, 0x0?})
        /home/user/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/applicationdef.go:84 +0x38 fp=0xc00012bf40 sp=0xc00012bee8 pc=0x53c278
main.main()
        /home/user/xxx/xxx/xxx/xxx/report/main.go:32 +0x74 fp=0xc00012bf80 sp=0xc00012bf40 pc=0x589f94
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc00012bfe0 sp=0xc00012bf80 pc=0x4384a7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00012bfe8 sp=0xc00012bfe0 pc=0x464ea1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040fb0 sp=0xc000040f90 pc=0x4388d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000040fe0 sp=0xc000040fb0 pc=0x438710
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000040fe8 sp=0xc000040fe0 pc=0x464ea1
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000041780 sp=0xc000041760 pc=0x4388d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000417c8 sp=0xc000041780 pc=0x424f6e
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000417e0 sp=0xc0000417c8 pc=0x41a226
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000417e8 sp=0xc0000417e0 pc=0x464ea1
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000066000?, 0x634cd0?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000041f70 sp=0xc000041f50 pc=0x4388d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x7db4a0)
        /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000041fa0 sp=0xc000041f70 pc=0x422e93
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000041fc8 sp=0xc000041fa0 pc=0x423465
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000041fe0 sp=0xc000041fc8 pc=0x41a1c6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x464ea1
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x7db8e0?, 0xe0?, 0x24?, 0xc000040770?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040628 sp=0xc000040608 pc=0x4388d6
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000407e0 sp=0xc000040628 pc=0x419267
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x464ea1
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:163 +0x45
exit status 2

```
But no problem with `colors.ClWhite` or other colors.  
```
package main

import (
    _ "github.com/ying32/govcl/pkgs/winappres"
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types/colors"
)

type TForm1 struct {
    *vcl.TForm
    PaintBox1 *vcl.TPaintBox
    ColorDialog1 *vcl.TColorDialog
    ToolBar1 *vcl.TToolBar
}

var Form1 *TForm1

func (f *TForm1) OnFormCreate(sender vcl.IObject) {
	f.PaintBox1 = vcl.NewPaintBox(f)
    f.PaintBox1.SetParent(f)
    
    canvas := f.PaintBox1.Canvas()
    // no problem with colors.ClBlack too
    canvas.Pen().SetColor(colors.ClWhite)
    canvas.Rectangle(0,0,100, 100)
}

func main() {

	vcl.Application.Initialize()
	vcl.Application.SetMainFormOnTaskBar(true)
	vcl.Application.CreateForm(&Form1)
	vcl.Application.Run()

}
```

Os: Q4OS 4.12.1-n1 (Gemini) (Debian 11.7 Based)

**Comment by ying32** [comment]
我没有Debian，但我在linux mint中尝试过，无法复现此错误。或者你可以尝试使用govcl dev分支的代码，并且自己编译liblcl项目dev分支的代码，看看是否可以解决这个问题。(I don't have Debian, but I tried it in Linux mint and can't reproduce this error. Or you can try to use the code of the govcl dev branch and compile the code of the liblcl project dev branch by yourself to see if you can solve this problem.)

**Comment by brokenarmor451** [comment]
> 我没有Debian，但我在linux mint中尝试过，无法复现此错误。或者你可以尝试使用govcl dev分支的代码，并且自己编译liblcl项目dev分支的代码，看看是否可以解决这个问题。(I don't have Debian, but I tried it in Linux mint and can't reproduce this error. Or you can try to use the code of the govcl dev branch and compile the code of the liblcl project dev branch by yourself to see if you can solve this problem.)

Thank you. I have tried govcl dev branch and it looks like the problem solved and I hope it does not appear in future.
