### ISSUE TITLE
centos 环境panic  goroutine ，window环境正常

### ISSUE THREAD

**Issue by jiangchengcai** [ying32/govcl#203]
<pre>SIGABRT: abort
PC=0x7fe9005e3387 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xdefda0, 0xc0015a5990, 0xc00120fa00)
	/home/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0015a5960 sp=0xc0015a5928 pc=0x41329b
github.com/ying32/dylib._Cfunc_Syscall3(0x7fe8d2962e00, 0x7fe8d2962e80, 0x1, 0x7fe8c45848f0, 0x0)
	_cgo_gotypes.go:180 +0x49 fp=0xc0015a5990 sp=0xc0015a5960 pc=0x521469
github.com/ying32/dylib.(*LazyProc).CallOriginal.func4(0xc00009e180, 0xc00120fae8, 0x3, 0x3, 0x52358f)
	/home/gowork/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:282 +0x11f fp=0xc0015a59e8 sp=0xc0015a5990 pc=0x52451f
github.com/ying32/dylib.(*LazyProc).CallOriginal(0xc00009e180, 0xc00120fae8, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
	/home/gowork/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:282 +0x275 fp=0xc0015a5a70 sp=0xc0015a59e8 pc=0x523bd5
github.com/ying32/dylib.(*LazyDLL).call(0xc000080040, 0xc00009e2d0, 0xc00120fe78, 0x1, 0x1, 0xc00120fed0, 0x1, 0x1, 0x0)
	/home/gowork/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:199 +0x105 fp=0xc0015a5e28 sp=0xc0015a5a70 pc=0x522725
github.com/ying32/dylib.(*LazyProc).Call(...)
	/home/gowork/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:264
github.com/ying32/govcl/vcl/api.Application_Run(0x7fe8c45848f0)
	/home/gowork/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/api/applicationdef.go:28 +0x8b fp=0xc0015a5e98 sp=0xc0015a5e28 pc=0x5264eb
github.com/ying32/govcl/vcl.(*TApplication).Run(...)
	/home/gowork/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/applicationdef.go:91
main.ServerStart()
	/mnt/hgfs/tusd_client/windows.go:100 +0x2c9 fp=0xc0015a5f68 sp=0xc0015a5e98 pc=0xdeebc9
main.main()
	/mnt/hgfs/tusd_client/main.go:7 +0x2f fp=0xc0015a5f88 sp=0xc0015a5f68 pc=0xdee72f
runtime.main()
	/home/go/src/runtime/proc.go:225 +0x256 fp=0xc0015a5fe0 sp=0xc0015a5f88 pc=0x448736
runtime.goexit()
	/home/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0015a5fe8 sp=0xc0015a5fe0 pc=0x47bf81

goroutine 6 [select, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc000210d00, 0x11f3c78, 0xc000276ac0)
	/home/go/src/database/sql/sql.go:1133 +0xb5
created by database/sql.OpenDB
	/home/go/src/database/sql/sql.go:740 +0x12a
</pre>

**Comment by jiangchengcai** [comment]
**
Pango:ERROR:../pango/pango-layout.c:3871:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
SIGABRT: abort
PC=0x7f5632795387 m=5 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f5632795387
stack: frame={sp:0x7f560a448a18, fp:0x0} stack=[0x7f5609c4a2a8,0x7f560a449ea8)
00007f560a448918:  725b205d736d3537  53205d313a73776f 
00007f560a448928:  6f63205443454c45  4620292a28746e75 
00007f560a448938:  73757460204d4f52  755f656c69665f64 
00007f560a448948:  57206064616f6c70  6f6f722045524548 
00007f560a448958:  30203d2064695f74  0000000000000000 
00007f560a448968:  0000000000000000  000000770000006e 
00007f560a448978:  0000000000000000  00007f560a4489af 
00007f560a448988:  00007f563284ebc9  0000000000000000 
00007f560a448998:  00007f56327d92f3  00007f560000007c 
00007f560a4489a8:  00007f5632b271c0  000000000000006d 
00007f560a4489b8:  000000000000006d  0000000000000002 
00007f560a4489c8:  8000000000000006  0000000000000000 
00007f560a4489d8:  0000000000000000  0000000000000000 
00007f560a4489e8:  00007f55f0012ab0  00007f5603848520 
00007f560a4489f8:  000000000000006a  00007f5602f15915 
00007f560a448a08:  00007f5602f1ece5  00007f5608e85730 
00007f560a448a18: <00007f5632796a78  0000000000000020 
00007f560a448a28:  0000000000000000  0000000000000000 
00007f560a448a38:  0000000000000000  0000000000000000 
00007f560a448a48:  0000000000000000  0000000000000000 
00007f560a448a58:  0000000000000000  0000000000000000 
00007f560a448a68:  0000000000000000  0000000000000000 
00007f560a448a78:  0000000000000000  0000000000000000 
00007f560a448a88:  0000000000000000  00000000000000

**Comment by jiangchengcai** [comment]
tusd_client: xcb_io.c:533: _XAllocID: Assertion `ret != inval_id' failed.
SIGABRT: abort
PC=0x7fb7a4d4d387 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xdefda0, 0xc0017bb990, 0xc0005b7a00)
	/home/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0017bb960 sp=0xc0017bb928 pc=0x41329b
github.com/ying32/dylib._Cfunc_Syscall3(0x7fb777163e00, 0x7fb777163e80, 0x1, 0x7fb77c17a8f0, 0x0)
	_cgo_gotypes.go:180 +0x49 fp=0xc0017bb990 sp=0xc0017bb960 pc=0x521469
github.com/ying32/dylib.(*LazyProc).CallOriginal.func4(0xc0000d8180, 0xc0005b7ae8, 0x3, 0x3, 0x52358f)
	/home/gowork/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:282 +0x11f fp=0xc0017bb9e8 sp=0xc0017bb990 pc=0x52451f
github.com/ying32/dylib.(*LazyProc).CallOriginal(0xc0000d8180, 0xc0005b7ae8, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
	/home/gowork/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:282 +0x275 fp=0xc0017bba70 sp=0xc0017bb9e8 pc=0x523bd5
github.com/ying32/dylib.(*LazyDLL).call(0xc0000ba040, 0xc0000d82d0, 0xc0005b7e78, 0x1, 0x1, 0xc0005b7ed0, 0x1, 0x1, 0x0)
	/home/gowork/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:199 +0x105 fp=0xc0017bbe28 sp=0xc0017bba70 pc=0x522725
github.com/ying32/dylib.(*LazyProc).Call(...)
	/home/gowork/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:264
github.com/ying32/govcl/vcl/api.Application_Run(0x7fb77c17a8f0)
	/home/gowork/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/api/applicationdef.go:28 +0x8b fp=0xc0017bbe98 sp=0xc0017bbe28 pc=0x5264eb
github.com/ying32/govcl/vcl.(*TApplication).Run(...)
	/home/gowork/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/applicationdef.go:91
main.ServerStart()

**Comment by jiangchengcai** [comment]
ui组件使用协程问题https://gitee.com/ying32/govcl/wikis/pages?sort_id=976890&doc_id=102420
