### ISSUE TITLE
MacOS下TEdit.Text()不能正确返回中文

### ISSUE THREAD

**Issue by AllenDang** [ying32/govcl#36]
MacOS v10.15.1
Go: 1.13.4 darwin/amd64
FPC: 3.0.4
LazarusIDE: 2.0.6
使用 MacOS 64bit编译

代码很简单，一个文本框，一个按钮，一个标签，如下。

```
type TForm1 struct {
    *vcl.TForm
    EdtName   *vcl.TEdit
    BtnSay    *vcl.TButton
    LbName    *vcl.TStaticText
    MainMenu1 *vcl.TMainMenu

    //::private::
    TForm1Fields
}

func (f *TForm1) OnBtnSayClick(sender vcl.IObject) {
	f.LbName3.SetCaption(fmt.Sprintf("Hello! %s", f.EdtName.Text()))
}
```

如果在文本框输入中文，点击两次按钮程序直接崩溃，错误日志如下

```
LoadLibrary: liblcl.dylib
IsloadedLcl: true
2019-12-11 16:29:09.973 gocode[43323:569442] *** Assertion failure in -[NSTextFieldCell _objectValue:forString:errorDescription:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1894.10.126/AppKit.subproj/NSCell.m:1417
2019-12-11 16:29:09.976 gocode[43323:569442] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: aString != nil'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff3395bf53 __exceptionPreprocess + 250
        1   libobjc.A.dylib                     0x00007fff69a21835 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff33977810 +[NSException raise:format:arguments:] + 88
        3   Foundation                          0x00007fff360575d1 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
        4   AppKit                              0x00007fff30b3a022 -[NSCell _objectValue:forString:errorDescription:] + 300
        5   AppKit                              0x00007fff30b39e4d -[NSCell setStringValue:] + 41
        6   AppKit                              0x00007fff30b8a7c9 -[NSControl setStringValue:] + 210
        7   liblcl.dylib                        0x0000000007ba7034 ControlScrollBar_StaticClassType + 2201044
        8   liblcl.dylib                        0x0000000007a3994f ControlScrollBar_StaticClassType + 704239
        9   liblcl.dylib                        0x0000000007a3fc8f ControlScrollBar_StaticClassType + 729647
        10  liblcl.dylib                        0x00000000079f450e ControlScrollBar_StaticClassType + 420526
        11  liblcl.dylib                        0x0000000007a4cb9b ControlScrollBar_StaticClassType + 782651
        12  liblcl.dylib                        0x000000000791ebf1 liblcl.dylib + 125937
        13  gocode                              0x0000000004300367 _cgo_1e7a236d0efc_Cfunc_Syscall4 + 39
        14  gocode                              0x0000000004058600 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff6aed349a m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4300340, 0xc000156798, 0x7e9d7b0)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc000156768 sp=0xc000156730 pc=0x400488b
github.com/ying32/govcl/vcl/dylib._Cfunc_Syscall4(0x7977478, 0x797c478, 0x2, 0x7e9eff0, 0xc000174030, 0x0)
        _cgo_gotypes.go:199 +0x4e fp=0xc000156798 sp=0xc000156768 pc=0x40d2c1e
github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal.func5(0xc00008e180, 0xc000156908, 0x4, 0x4, 0x3)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:287 +0x18b fp=0xc000156800 sp=0xc000156798 pc=0x40d5d6b
github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal(0xc00008e180, 0xc000156908, 0x4, 0x4, 0x3, 0x3, 0x4, 0x0)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:287 +0x133 fp=0xc000156878 sp=0xc000156800 pc=0x40d51f3
github.com/ying32/govcl/vcl/dylib.(*LazyDLL).call(0xc0000220c0, 0xc0000c25a0, 0xc000156c88, 0x2, 0x2, 0x20, 0x46791a0, 0x4356b20, 0xc000178000)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:207 +0x1ba fp=0xc000156c30 sp=0xc000156878 pc=0x40d400a
github.com/ying32/govcl/vcl/dylib.(*LazyProc).Call(...)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:267
github.com/ying32/govcl/vcl/api.StaticText_SetCaption(0x7e9eff0, 0xc000174020, 0xb)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/api/importFuncsAuto.go:14894 +0x8d fp=0xc000156ce0 sp=0xc000156c30 pc=0x40fb6ed
github.com/ying32/govcl/vcl.(*TStaticText).SetCaption(...)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/statictext.go:562
main.(*TForm1).OnBtnSayClick(0xc00014b140, 0x4404280, 0xc00016cf40)
        /Users/allendang/Desktop/vlctest/gocode/Form1Impl.go:17 +0xcd fp=0xc000156d40 sp=0xc000156ce0 pc=0x42f71dd
runtime.call32(0xc00014b6b0, 0xc000011248, 0xc00016cf20, 0x1800000018)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:539 +0x3b fp=0xc000156d70 sp=0xc000156d40 pc=0x405716b
reflect.callMethod(0xc000022180, 0xc000156e50, 0xc000156e38)
        /usr/local/Cellar/go/1.13.4/libexec/src/reflect/value.go:714 +0x1f0 fp=0xc000156e20 sp=0xc000156d70 pc=0x407eda0
reflect.methodValueCall(0x4404280, 0xc00016cf40, 0xc000157438, 0x4331560, 0xc000022180, 0x4035d01, 0x4005a55, 0xc000156ec8, 0x4035f8f, 0xc000024000, ...)
        /usr/local/Cellar/go/1.13.4/libexec/src/reflect/asm_amd64.s:35 +0x42 fp=0xc000156e50 sp=0xc000156e20 pc=0x40879d2
github.com/ying32/govcl/vcl.eventCallbackProc(0x98222819, 0x7ffeefbfd950, 0x1, 0xc000157810)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/callbackevent.go:50 +0x3b8 fp=0xc0001577a8 sp=0xc000156e50 pc=0x4293418
github.com/ying32/govcl/vcl.doEventCallbackProc(...)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/callback_posix.go:28
github.com/ying32/govcl/vcl._cgoexpwrap_7521bf8818ec_doEventCallbackProc(0x98222819, 0x7ffeefbfd950, 0x1, 0x0)
        _cgo_gotypes.go:86 +0x82 fp=0xc000157810 sp=0xc0001577a8 pc=0x42eb8c2
runtime.call32(0x0, 0x7ffeefbfd7d0, 0x7ffeefbfd860, 0x20)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:539 +0x3b fp=0xc000157840 sp=0xc000157810 pc=0x405716b
runtime.cgocallbackg1(0x0)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/cgocall.go:314 +0x1b7 fp=0xc000157928 sp=0xc000157840 pc=0x4004c37
runtime.cgocallbackg(0x0)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/cgocall.go:191 +0xc1 fp=0xc000157990 sp=0xc000157928 pc=0x40049e1
runtime.cgocallback_gofunc(0x40048af, 0x4300300, 0xc000157a20, 0xc000157a10)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:793 +0x9b fp=0xc0001579b0 sp=0xc000157990 pc=0x405873b
runtime.asmcgocall(0x4300300, 0xc000157a20)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:640 +0x42 fp=0xc0001579b8 sp=0xc0001579b0 pc=0x40585d2
runtime.cgocall(0x4300300, 0xc000157a20, 0xc000157ae0)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/cgocall.go:131 +0x7f fp=0xc0001579f0 sp=0xc0001579b8 pc=0x40048af
github.com/ying32/govcl/vcl/dylib._Cfunc_Syscall3(0x7977478, 0x79774a8, 0x1, 0x7e988f0, 0x0)
        _cgo_gotypes.go:183 +0x4e fp=0xc000157a20 sp=0xc0001579f0 pc=0x40d2b2e
github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal.func4(0xc00008e180, 0xc000157b68, 0x3, 0x3, 0x8)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:285 +0x143 fp=0xc000157a78 sp=0xc000157a20 pc=0x40d5ba3
github.com/ying32/govcl/vcl/dylib.(*LazyProc).CallOriginal(0xc00008e180, 0xc000157b68, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:285 +0x197 fp=0xc000157af0 sp=0xc000157a78 pc=0x40d5257
github.com/ying32/govcl/vcl/dylib.(*LazyDLL).call(0xc0000220c0, 0xc00014a270, 0xc000157ef0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:205 +0x100 fp=0xc000157ea8 sp=0xc000157af0 pc=0x40d3f50
github.com/ying32/govcl/vcl/dylib.(*LazyProc).Call(...)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/dylib/dylib_posix.go:267
github.com/ying32/govcl/vcl/api.Application_Run(0x7e988f0)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/api/applicationdef.go:14 +0x65 fp=0xc000157f08 sp=0xc000157ea8 pc=0x40d7ea5
github.com/ying32/govcl/vcl.(*TApplication).Run(...)
        /Users/allendang/Documents/Gocode/src/github.com/ying32/govcl/vcl/applicationdef.go:86
main.main()
        /Users/allendang/Desktop/vlctest/gocode/main.go:12 +0xd8 fp=0xc000157f60 sp=0xc000157f08 pc=0x42f72d8
runtime.main()
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/proc.go:203 +0x21e fp=0xc000157fe0 sp=0xc000157f60 pc=0x402ec0e
runtime.goexit()
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000157fe8 sp=0xc000157fe0 pc=0x4058e61

rax    0x0
rbx    0xc676dc0
rcx    0x7ffeefbfb8b8
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbfb8e0
rsp    0x7ffeefbfb8b8
r8     0x7ffeefbfb780
r9     0x7ffeefbfb950
r10    0x0
r11    0x246
r12    0x307
r13    0x3000000008
r14    0x6
r15    0x16
rip    0x7fff6aed349a
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
WARNING: TButton.Destroy with LCLRefCount>0. Hint: Maybe the component is processing an event?
```

**Comment by AllenDang** [comment]
我下载了预编译的 MacOS 64bit的库也是一样的结果

**Comment by AllenDang** [comment]
```
f.EdtName.SetText("你好")
fmt.Println([]rune(f.EdtName.Text()))
```

打印出来的结果是 [65533 65533]

**Comment by ying32** [comment]
1、第一个错误看日志像是TStaticText控件有问题，一般用于标签显示的话用TLabel控件。
2、你直接`fmt.Println(f.EdtName.Text()) `出来的结果是什么，是中文还是？

**Comment by AllenDang** [comment]
@ying32 直接打印的结果是乱码，看rune打印的结果可知，65533这已经超过正常字符的范围了。

**Comment by ying32** [comment]
最近mac不在身边，有得调试环境，你这个问题暂时没办法解决😳

**Comment by ying32** [comment]
你是用的主分支的代码么？还有1.2.6.4的liblcl.dylib

**Comment by AllenDang** [comment]
@ying32 我用的是主分支的代码。liblcl.dylib 分别使用了我自己编译的和你预编译的版本，结果都一样。

**Comment by ying32** [comment]
我看你用的是 go1.13.4，你可以尝试下go 1.13版本以下的，这次因为go1.13版本开始GC上出现了收回问题，或许跟这个有关。前几天就是因为传入的字符串遇到了这个问题，我想你这个有可能是同一个问题。

**Comment by ying32** [comment]
已经修复了，在MacOS下测试正常了。
