### ISSUE TITLE
圆图画线出现闪退

### ISSUE THREAD

**Issue by liangzi2019** [ying32/govcl#95]
### go.mod
```golang
module govclui

go 1.17

require github.com/ying32/govcl v2.0.11-0.20211027115815-0f4720d3bd80+incompatible

require (
	github.com/ying32/dylib v0.0.0-20210414124638-bf395b2d391a // indirect
	github.com/ying32/liblclbinres v0.0.0-20210305091625-aea78f1f52c0 // indirect
)
```

### main.go
```golang
package main

import (
	"math"

	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types/colors"
)

type TForm struct {
	*vcl.TForm
	PaintBox, PaintBox1    *vcl.TPaintBox
	btn1, btn2, btn3, btn4 *vcl.TButton
}

var mainForm *TForm

func main() {
	vcl.RunApp(&mainForm)
}
func (f *TForm) OnFormCreate(sender vcl.IObject) {
	f.SetCaption("测试画图清除")
	f.SetWidth(1200)
	f.SetHeight(1200)
	f.ScreenCenter()
	//
	f.initPaintBoxPaint()
	//
	f.btn1 = vcl.NewButton(f)
	f.btn1.SetParent(f)
	f.btn1.SetLeft(30)
	f.btn1.SetTop(30)
	f.btn1.SetCaption("画线1")
	f.btn1.SetOnClick(func(sender vcl.IObject) {
		f.OnPaintBoxPaint(sender)
	})

	f.btn2 = vcl.NewButton(f)
	f.btn2.SetParent(f)
	f.btn2.SetLeft(120)
	f.btn2.SetTop(30)
	f.btn2.SetCaption("clean")
	f.btn2.SetOnClick(func(sender vcl.IObject) {
		f.PaintBox.Free()
	})

	f.btn3 = vcl.NewButton(f)
	f.btn3.SetParent(f)
	f.btn3.SetLeft(30)
	f.btn3.SetTop(60)
	f.btn3.SetCaption("画线2")
	f.btn3.SetOnClick(func(sender vcl.IObject) {
		f.OnPaintBoxPaint1(sender)
	})

	f.btn4 = vcl.NewButton(f)
	f.btn4.SetParent(f)
	f.btn4.SetLeft(120)
	f.btn4.SetTop(60)
	f.btn4.SetCaption("clean")
	f.btn4.SetOnClick(func(sender vcl.IObject) {
		f.PaintBox1.Free()
	})
}
func (f *TForm) initPaintBoxPaint() {
	f.PaintBox = vcl.NewPaintBox(f)
	f.PaintBox.SetParent(f)

	f.PaintBox1 = vcl.NewPaintBox(f)
	f.PaintBox1.SetParent(f)
}
func (f *TForm) OnPaintBoxPaint(sender vcl.IObject) {
	f.PaintBox.Free()
	f.PaintBox = vcl.NewPaintBox(f)
	f.PaintBox.SetParent(f)
	f.PaintBox.SetBounds(10+80, 10+80, 800, 800)
	canvas := f.PaintBox.Canvas()
	f.PaintBox.SetOnPaint(func(sender vcl.IObject) {
		pen := canvas.Pen()
		pen.SetColor(colors.ClSkyblue)
		pen.SetWidth(2)
		brush := canvas.Brush()
		brush.SetColor(colors.ClSkyblue)
		r := f.PaintBox.ClientRect()
		canvas.Ellipse(1, 1, r.Width()-1, r.Height()-1)
		angle := 0.0
		cp := r.CenterPoint()

		for i := 0; i < 60; i++ {
			var len int
			//刻度，每五分钟一次
			if i%5 == 0 {
				len = 12
				pen.SetWidth(2)
			} else {
				len = 300
				pen.SetWidth(1)
			}
			pen.SetColor(colors.ClTeal)
			sline := cp.X - pen.Width()
			canvas.MoveTo(int32(math.Trunc(float64(cp.X)+float64(sline)*math.Cos(angle))),
				int32(math.Trunc(float64(cp.Y)+float64(sline)*math.Sin(angle))))
			sline -= int32(len)
			canvas.LineTo(int32(math.Trunc(float64(cp.X)+float64(sline)*math.Cos(angle))),
				int32(math.Trunc(float64(cp.Y)+float64(sline)*math.Sin(angle))))
			angle += math.Pi / 30.0
		}
	})
}

func (f *TForm) OnPaintBoxPaint1(sender vcl.IObject) {
	f.PaintBox1.Free()
	f.PaintBox1 = vcl.NewPaintBox(f)
	f.PaintBox1.SetParent(f)
	f.PaintBox1.SetBounds(10+80, 10+80, 800, 800)
	canvas := f.PaintBox1.Canvas()
	f.PaintBox1.SetOnPaint(func(sender vcl.IObject) {
		pen := canvas.Pen()
		pen.SetColor(colors.ClRed)
		pen.SetWidth(2)
		brush := canvas.Brush()
		brush.SetColor(colors.ClBlack)
		r := f.PaintBox1.ClientRect()
		canvas.Ellipse(1, 1, r.Width()-1, r.Height()-1)
		angle := 0.0
		cp := r.CenterPoint()
		for i := 0; i < 60; i++ {
			var len int
			//刻度，每五分钟一次
			if i%5 == 0 {
				len = 300
				pen.SetWidth(2)
			} else {
				len = 12
				pen.SetWidth(1)
			}
			pen.SetColor(colors.ClTeal)

			sline := cp.X - pen.Width()
			canvas.MoveTo(int32(math.Trunc(float64(cp.X)+float64(sline)*math.Cos(angle))),
				int32(math.Trunc(float64(cp.Y)+float64(sline)*math.Sin(angle))))
			sline -= int32(len)
			canvas.LineTo(int32(math.Trunc(float64(cp.X)+float64(sline)*math.Cos(angle))),
				int32(math.Trunc(float64(cp.Y)+float64(sline)*math.Sin(angle))))
			angle += math.Pi / 30.0
		}
	})
}
```
### 闪退报错内容
```text
Library Version: 2.0.10
WARNING: TGoForm.Destroy with LCLRefCount>0. Hint: Maybe the component is processing an event?
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xa9ed4b]

goroutine 1 [running, locked to thread]:
github.com/ying32/govcl/vcl.(*TPen).SetColor(...)
	C:/Users/Amrta/go/pkg/mod/github.com/ying32/govcl@v2.0.11-0.20211027115815-0f4720d3bd80+incompatible/vcl/pen.go:213
main.(*TForm).OnPaintBoxPaint.func1({0xacd660, 0xc00000b450})
	E:/src/draw1/main.go:80 +0x4b
github.com/ying32/govcl/vcl.eventCallbackProc(0xc000107788, 0x5e93dfe6e0, 0x1)
	C:/Users/Amrta/go/pkg/mod/github.com/ying32/govcl@v2.0.11-0.20211027115815-0f4720d3bd80+incompatible/vcl/callbackevent.go:91 +0x2bc
syscall.Syscall(0x110005710, 0x3, 0x110003590, 0x1, 0x1dfb0f7fe30)
	E:/Program Files/Go/src/runtime/syscall_windows.go:479 +0xf4
syscall.(*Proc).Call(0x92cd27, {0xc0000129d8, 0xace700, 0x1})
	E:/Program Files/Go/src/syscall/dll_windows.go:187 +0x185
syscall.(*LazyProc).Call(0xc00007a4b0, {0xc0000129d8, 0x3, 0x3})
	E:/Program Files/Go/src/syscall/dll_windows.go:340 +0x50
github.com/ying32/dylib.(*LazyDLL).call(0xc000042230, 0xc000042290, {0xc00000a8d0, 0xc000107f28, 0x1})
	C:/Users/Amrta/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20210414124638-bf395b2d391a/dylib_windows.go:65 +0x1b1
github.com/ying32/dylib.(*LazyProc).Call(...)
	C:/Users/Amrta/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20210414124638-bf395b2d391a/dylib_windows.go:104
github.com/ying32/govcl/vcl/api.Application_Run(0x1dfb0f7fe30)
	C:/Users/Amrta/go/pkg/mod/github.com/ying32/govcl@v2.0.11-0.20211027115815-0f4720d3bd80+incompatible/vcl/api/applicationdef.go:28 +0x7e
github.com/ying32/govcl/vcl.(*TApplication).Run(...)
	C:/Users/Amrta/go/pkg/mod/github.com/ying32/govcl@v2.0.11-0.20211027115815-0f4720d3bd80+incompatible/vcl/applicationdef.go:91
github.com/ying32/govcl/vcl.RunApp({0xc000107f60, 0x1, 0x938045})
	C:/Users/Amrta/go/pkg/mod/github.com/ying32/govcl@v2.0.11-0.20211027115815-0f4720d3bd80+incompatible/vcl/funcs.go:185 +0xf5
main.main()
	E:/src/draw1/main.go:19 +0x45
```

### 偶然不闪退 会出现如下错误
![2021-11-15_06-22](https://user-images.githubusercontent.com/50795684/141701043-2637c225-9314-40dc-953a-6a2e42924355.png)
然后就会出现划线位置不对了跑到左上角了 如下图

![2021-11-15_06-23](https://user-images.githubusercontent.com/50795684/141701075-82a299c0-bd6b-426e-ba93-62b4389c8728.png)

### 希望的效果
- 点击画图1画对应的线 clean 清除画线
- 点击画图2画对应的线 clean 清除画线
如下图
![image](https://user-images.githubusercontent.com/50795684/141701139-e129fa13-8cc2-48e6-9a04-5865ba734066.png)

**Comment by liangzi2019** [comment]
问题已解决 谢谢作者的解答
